# Generated by Django 4.2.3 on 2023-08-05 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("campains", "0001_initial"),
        ("index", "0003_cart_cartitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="campaign",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="campains.campaign",
            ),
        ),
    ]
