# Generated by Django 4.2.3 on 2023-08-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0005_product_discounted_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShippingFee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "limit_amount",
                    models.DecimalField(decimal_places=2, default=300, max_digits=10),
                ),
                (
                    "free_shipping_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
            ],
        ),
    ]
