# Generated by Django 4.2.3 on 2023-08-05 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0006_shippingfee"),
    ]

    operations = [
        migrations.RemoveField(model_name="shippingfee", name="free_shipping_fee",),
    ]
