# Generated by Django 4.2.3 on 2023-08-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0008_remove_shippingfee_limit_amount_shippingfee_limit"),
    ]

    operations = [
        migrations.AddField(
            model_name="shippingfee",
            name="kargo_bedeli",
            field=models.DecimalField(
                decimal_places=2, default=20, max_digits=10, verbose_name="Kargo Ücreti"
            ),
        ),
    ]
